### ISSUE TITLE
Q: dbfield.float read_from_array use delocalize_number

### ISSUE THREAD

**Issue by hwde** [gerdriesselmann/gyro-php#28]
Hi Gerd,

I've an issue with dbfield.float ... but only on external server, not locally in docker development. Maybe you've an idea:
- app/constants.php has a define('APP_LANG', 'de');
- my MySQL table contains a field with decimal(12,2)

Whenever I type something in remote server forms for that field, i.e. "1", after form has been saved the form updates to the DB value "1.00" (which is what I expect). But next time I save the form, "1.00" will be delocalized (from dbfield.float read_from_array() to 100, so the the number updates to "100", which is wrong.

I would expect that GyroString::localize_number has to be called somewhere, so that the form values contains "1,00" instead of "1.00", so delocalize_number makes sense ... but core never called it.

I assume date.timezone = Europe/Berlin (which is used on external server) cause the issue?

**Comment by hwde** [comment]
Maybe it would be a better solution to add a config option to turn of number localization, as most time users would not expect localized numbers?

**Comment by gerdriesselmann** [comment]
Hmm, read_from_array() should be invoked for user input like $_POST, not DB results. Can you figure where it is called in the context of a DB request?

**Comment by hwde** [comment]
It is called only on user input. Currently I fixed it with a workaround:

```
class FixmeDBFieldFloat extends DBFieldFloat {
    public function read_from_array($arr) {
        error_log("parent would return=".parent::read_from_array($arr));
        return Arr::get_item($arr, $this->get_field_name(), null);
    }
}

```

If I type "1.23" into an <input type="text"> field into the form, I see in error.log:

```
parent would return=123
```

And still, I get the correct value "1.23" in dev-environment.

**Comment by gerdriesselmann** [comment]
It all boils down to GyroString::delocalize_number(), which is using settings retrieved from localeconv().

Can you include the output of localeconv() in the error log?

Generally, if you enter 1.23 into a form with German language settings, the dot gets interpreted as thousands separator, and is therefore ignored. On the other hand 1,23 would be turned into 1.23 which than can be used for DB or internally as a valid floating number.

To avoid this, the output into the form element needs indeed to be localized using GyroString::localize_number(). I noticed, there is no WidgetInput for floating point numbers, which would do the conversion automatically, so I created one.

Try

```
print WidgetInput::output('my_num', 'Enter amount', $form_data, WIdgetInput::FLOAT);
```

**Comment by gerdriesselmann** [comment]
The new Widget type is currently on the dev branch only.

**Comment by hwde** [comment]
output of localeconv() seems to be the same on remote and local:

```
array (
  | 'decimal_point' => '.',
  | 'thousands_sep' => '',
  | 'int_curr_symbol' => '',
  | 'currency_symbol' => '',
  | 'mon_decimal_point' => '',
  | 'mon_thousands_sep' => '',
  | 'positive_sign' => '',
  | 'negative_sign' => '',
  | 'int_frac_digits' => 127,
  | 'frac_digits' => 127,
  | 'p_cs_precedes' => 127,
  | 'p_sep_by_space' => 127,
  | 'n_cs_precedes' => 127,
  | 'n_sep_by_space' => 127,
  | 'p_sign_posn' => 127,
  | 'n_sign_posn' => 127,
  | 'grouping' =>
  | array (
  | ),
  | 'mon_grouping' =>
  | array (
  | ),
  | )

```

**Comment by hwde** [comment]
I'll try the widget ...

**Comment by hwde** [comment]
WIdgetInput::FLOAT works as expected. A little bit unexpectedly to "enter" numbers with "," as decimal "point", but works as expected. Guess I have to accept both "." and "," as decimal point (without any thousand separator).

**Comment by gerdriesselmann** [comment]
On a system configured with language "de", the number format is also German, which means thousands are separated by a dot, and the fraction is separated by a comma.

If you want German translations, but English number format, you can try calling

```setlocale(LC_NUMERIC, 'C');```

in index.php, right after Gyro was initialized. Gyro should respect this.
